# Site
repository: SionAn.github.io #sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sion An
title: Ph.D. Candidate, Department of Robotics and Mechatronics Engineering, DGIST
email: sionan624@gmail.com
#website: SionAn.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  SionAn
# stackoverflow_username: "00000001"
# dribbble_username: SionAn
# facebook_username: SionAn
# flickr_username: SionAn
#instagram_username: SionAn
#linkedin_username: SionAn
# xing_username: SionAn
# pinterest_username: SionAn
#youtube_username: SionAn
# googleplus_username: +SionAn
orcid_username: 0000-0002-3800-7158

# Additional icon links
additional_links:
  - title: Google Scholar
    icon: fas fa-graduation-cap  #fab fa-google
    url: https://scholar.google.com/citations?user=fr1Fb5UAAAAJ&hl=ko

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/SionAn.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Ph.D. Candidate in <a href="https://sites.google.com/view/mispl/home" target="_blank">Medical Image and Signal Processing Laboratory</a> at Daegu Gyeongbuk Institute of Science and Technology (DGIST) advised by <a href="https://sites.google.com/view/mispl/members/professor" target="_blank">Professor Sang Hyun Park</a>.
  I obtained my B.S. from DGIST in February 2020. 
  
  I am interested in developing deep learning algorithms for tailored solutions. 
  Specifically, my research focuses on personalized and targeted tasks using meta-learning and transfer learning techniques to build AI solutions that perform effectively with limited labeled data and supplementary information. 
  This facilitates the application of AI across diverse domains, including brain signal analysis and anomaly detection.

  Keywords: <mark>Meta-Learning</mark>, <mark>Transfer Learning</mark>, <mark>Medical Image and Signal Processing</mark>, <mark>Brain-Computer Interfaces</mark>

content:
  - title: Education
    layout: list
    content:
      - layout: left
        sub_title: 2020.03 - Present
        description: <b>Combined Undergraduate-Graduate Program</b>, Department of Robotics and Mechatronics Engineering, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.
      - layout: left
        sub_title: 2015.03 - 2020.02
        description: <b>Bachelor of Engineering</b>, School of Undergraduate Studies, Daegu Gyeongbuk Institute of Science and Technology (DGIST), Daegu, South Korea.

  - title: Research Experiences # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: 2024.01 - 2024.12
        description: <b>Visiting Student</b> at <a href="https://www.med.upenn.edu/shenlab/" target="_blank">Shen Lab</a>, University of Pennsylvania advised by Professor Li Shen
      - layout: left
        sub_title: 2017.03 - 2017.12
        description: <b>Undergraduate Group Research Program (UGRP)</b> at <a href="https://dgist-lab.wixsite.com/brainlab" target="_blank">BRAINLab</a>, DGIST advised by Professor Jinung An
      - layout: left
        sub_title: 2017.01 - 2018.02
        description: <b>Undergraduate Research Assistant</b> at <a href="https://mems.dgist.ac.kr/" target="_blank">DEMRC</a>, DGIST advised by Professor Hongsoo Choi

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Articles in Submission/Preparation

      - layout: left
        sub_title: Under Review
        authors: An, S., Kang, M., Kim, S., Chikontwe, P., Shen, L., & Park, S. H.
        papertitle: Resting State EEG Signal based Subject-Adaptive Meta-Learning for Brain-Computer Interfaces

      - layout: left
        sub_title: Under Review
        authors: Lee, S., Kim, S., An, S., Park, S. H., & Lee, S.
        papertitle: Few-Shot Logical Anomaly Detection with Text-based Logics via Language-Image Contrastive Training

      - layout: left
        sub_title: Under Review
        authors: Kim, S., Lee, K., An, S., Chikontwe, P., Kang, M., Adeli, E., Pohl, K. M., & Park, S. H.
        papertitle: Semantic Context Guided Industrial Anomaly Detection with Semi-Supervised Few-Shot Part Segmentation


      - layout: top-middle
        title: Journal Articles

      - layout: left
        sub_title: 2024
        index: J5
        paper_link:
          url: https://doi.org/10.1016/j.eswa.2024.124890
        authors: An, S., Kim, J., Kim, S., Chikontwe, P., Jung, J., Jeon, H., & Park, S. H.
        papertitle: Few shot Anomaly Detection using Positive Unlabeled Learning with Cycle Consistency and Co-occurrence Features
        publisher: Expert Systems with Applications (ESWA)

      - layout: left
        sub_title: 2024
        index: J4
        paper_link:
          url: https://doi.org/10.1016/j.neunet.2024.106505
        authors: Ullah, I., An, S., Chikontwe, P., Kang, M., Choi, J., & Park, S. H.
        papertitle: Video Domain Adaptation for Semantic Segmentation using Perceptual Consistency Matching
        publisher: Neural Networks (NN)

      - layout: left
        sub_title: 2023
        index: J3
        paper_link:
          url: https://doi.org/10.1109/TNNLS.2023.3287181
        code_link:
          url: https://github.com/SionAn/FewShotEEG
        others:
          url: https://m.hankookilbo.com/News/Read/A2023082309580001583
        authors: An, S., Kim, S., Chikontwe, P., & Park, S. H.
        papertitle: Dual Attention Relation Network with Fine-Tuning for Few Shot EEG Motor Imagery Classification
        publisher: IEEE Transactions on Neural Networks and Learning Systems (TNNLS)

      - layout: left
        sub_title: 2023
        index: J2
        paper_link:
          url: https://doi.org/10.1016/j.patcog.2022.109292
        authors: Kim, S., Chikontwe, P., An, S., & Park, S. H.
        papertitle: Uncertainty-aware semi-supervised few shot segmentation
        publisher: Pattern Recognition (PR)

      - layout: left
        sub_title: 2022
        index: J1
        paper_link:
          url: https://doi.org/10.1109/TOH.2022.3177714
        authors: Cha, H., An, S., Choi, S., Yang, S., Park, S. H., Park, S.
        papertitle: Study on Intention Recognition and Sensory Feedback Control of Robotic Prosthetic Hand Through EMG Classification and Proprioceptive Feedback Using Rule-based Haptic Device
        publisher: IEEE Transactions on Haptics (ToH)


      - layout: top-middle
        title: International Conference Papers

      - layout: left
        sub_title: 2024
        index: C7
        paper_link:
          url: https://arxiv.org/abs/2405.19346
        code_link:
          url: https://github.com/SionAn/MICCAI2024-ResTL
        authors: An, S., Kang, M., Kim, S., Chikontwe, P., Shen, L., & Park, S. H.
        papertitle: Subject-Adaptive Transfer Learning Using Resting State EEG Signals for Cross-Subject EEG Motor Imagery Classification
        publisher: International Conference on Medical Image Computing and Computer-Assisted Intervention (MICCAI) (Early Accept<Top11%)

      - layout: left
        sub_title: 2024
        index: C6
        authors: An, S., Shen. L., & Park, S. H.
        papertitle: Motor Imagery EEG Signal Generation from Resting-State Signal
        publisher: Annual International Conference of the IEEE Engineering in Medicine & Biology Society Research Poster (EMBC Research Poster)

      - layout: left
        sub_title: 2024
        index: C5
        paper_link:
          url: https://ojs.aaai.org/index.php/AAAI/article/view/28703
        authors: Kim, S., An, S., Chikontwe, P., Kang, M., Adeli, E., Phol, K. M., & Park, S. H.
        papertitle: Few Shot Part Segmentation Reveals Compositional Logic for Industrial Anomaly Detection
        publisher: AAAI Conference on Artificial Intelligence (AAAI)

      - layout: left
        sub_title: 2021
        index: C4
        paper_link:
          url: https://ojs.aaai.org/index.php/AAAI/article/view/16275
        authors: Kim, S., An, S., Chikontwe, P., & Park, S. H.
        papertitle: Bidirectional RNN-based few shot learning for 3d medical image segmentation
        publisher: AAAI Conference on Artificial Intelligence (AAAI)

      - layout: left
        sub_title: 2021
        index: C3
        paper_link:
          url: https://link.springer.com/chapter/10.1007/978-3-030-87602-9_1
        authors: Won, D., Jung, E., An, S., Chikontwe, P., & Park, S. H.
        papertitle: Low-Dose CT Denoising Using Pseudo-CT Image Pairs
        publisher: MICCAI PRIME (International Workshop on PRedictive Intelligence In MEdicine)

      - layout: left
        sub_title: 2020
        index: C2
        paper_link:
          url: https://link.springer.com/chapter/10.1007/978-3-030-59354-4_7
        authors: Won, D., An, S., Park, S. H., & Ye, D. H.
        papertitle: Low-dose CT denoising using octave convolution with high and low frequency bands
        publisher: MICCAI PRIME (International Workshop on PRedictive Intelligence In MEdicine)

      - layout: left
        sub_title: 2020
        index: C1
        paper_link:
          url: https://ieeexplore.ieee.org/abstract/document/9340933
        code_link:
          url: https://github.com/SionAn/FewShotEEG
        authors: An, S., Kim, S., Chikontwe, P., & Park, S. H.
        papertitle: Few-Shot Relation Learning with Attention for EEG-based Motor Imagery Classification
        publisher: IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS)

      - layout: top-middle
        title: Domestic Conference Papers

      - layout: left
        sub_title: 2024
        index: D6
        paper_link:
          url: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11765573
        authors: Choi, Y., Ryu, C., Kim, H., Park, H., An, S., Park, S. H., & Kim, H.
        papertitle: Robot gripper integrated thermal sensor based on pyroelectric effect
        publisher: The Korean Society of Mechanical Engineers Annual Meeting
      - layout: left
        sub_title: 2023
        index: D5
        authors: Lee, D., An, S., & Park, S. H.
        papertitle: Anomaly Detection on Abdominal CT and Brain MRI based on Densitiy-Estimation
        publisher: Workshop on Image Processing and Image Understanding (IPIU)

      - layout: left
        sub_title: 2022
        index: D4
        paper_link:
          url: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE11132672
        authors: An, S., Kim, S., Chikontwe, P., Park, H., Abdul, T., & Park, S. H.
        papertitle: Dual Attention Relation Network for Few Shot EEG Motor Imagery Classification
        publisher: Summer Annual Conference of IEIE

      - layout: left
        sub_title: 2021
        index: D3
        authors: Kim, S., An, S., Chikontwe, P., & Park, S. H.
        papertitle: Few Shot Learning based on Bidirectional Recurrent Neural Network for 3D Medical Image Segmentation
        publisher: Workshop on Image Processing and Image Understanding (IPIU)

      - layout: left
        sub_title: 2020
        index: D2
        authors: An, S., Kim, S., & Park, S. H.
        papertitle: Neural Spike Detection using Deep Convolutional Neural Network
        publisher: Workshop on Image Processing and Image Understanding (IPIU)

      - layout: left
        sub_title: 2017
        index: D1
        paper_link:
          url: https://www.dbpia.co.kr/journal/articleDetail?nodeId=NODE07288378
        authors: Lee, H., An, S., Jeon, S., Kim, K., Lee, S., Lee, S., Kim, J. Y., & Choi, H.
        papertitle: Development of Helical Drilling Microrobot Based on Catheter and Guidewire for Chronic Total Occlusion Treatment
        publisher: The Korean Society of Mechanical Engineers Annual Meeting

  - title: Review Services
    layout: text
    content: |
      - Medical Image Analysis
      - IEEE Transactions on Industrial Informatics (TII)
      - IEEE Transactions on Neural Networks and Learning Systems (TNNLS)
      - IEEE Transactions on Neural Systems and Rehabilitation Engineering (TNSRE)
      - Neural Networks (NN)
      - Cognitive Neurodynamics
      - International Conference on Medical Image Computing and Computer Assisted Intervention (MICCAI)
      - International Conference on Bioinformatics and Biomedicine (BIBM)

  - title: Awards
    layout: text
    content: |
      - (2023) DGIST Outstanding Researcher Award
      - (2023) DGIST Post-Graduate Research Abroad Awards
      - (2023) Industry-Academia Scholarship from the CTO team at LG Electronics
      - (2021) Ranked 3rd in SNUH Sleep AI Challenge

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
